/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

// AUTO-GENERATED by DataProcessing/generate_balancing_authorities.py - do not edit by hand.
// Constant names are derived from the EIA respondent name; values are EIA-930 codes.

namespace QuantConnect.DataSource
{
    /// <summary>
    /// Readable named constants for EIA-930 balancing authority codes, for use as the ticker in
    /// <c>AddData&lt;EIAElectricity&gt;(EIA.BalancingAuthorities.X)</c>. The major operators also
    /// carry their common short name (ERCOT, CAISO, NYISO, ISONE, SPP, BPA).
    /// </summary>
    public static partial class EIA
    {
        /// <summary>EIA-930 balancing authority codes by readable name.</summary>
        public static class BalancingAuthorities
        {
            /// <summary>PowerSouth Energy Cooperative</summary>
            public const string PowerSouthEnergyCooperative = "AEC";
            /// <summary>Associated Electric Cooperative, Inc.</summary>
            public const string AssociatedElectricCooperativeInc = "AECI";
            /// <summary>Avista Corporation</summary>
            public const string AvistaCorporation = "AVA";
            /// <summary>Avangrid Renewables, LLC</summary>
            public const string AvangridRenewablesLlc = "AVRN";
            /// <summary>Arizona Public Service Company</summary>
            public const string ArizonaPublicServiceCompany = "AZPS";
            /// <summary>Balancing Authority of Northern California</summary>
            public const string BalancingAuthorityOfNorthernCalifornia = "BANC";
            /// <summary>Bonneville Power Administration</summary>
            public const string BPA = "BPAT";
            /// <summary>Bonneville Power Administration</summary>
            public const string BonnevillePowerAdministration = "BPAT";
            /// <summary>California</summary>
            public const string California = "CAL";
            /// <summary>Carolinas</summary>
            public const string Carolinas = "CAR";
            /// <summary>Central</summary>
            public const string Central = "CENT";
            /// <summary>Public Utility District No. 1 of Chelan County</summary>
            public const string PublicUtilityDistrictNo1OfChelanCounty = "CHPD";
            /// <summary>California Independent System Operator</summary>
            public const string CAISO = "CISO";
            /// <summary>California Independent System Operator</summary>
            public const string CaliforniaIndependentSystemOperator = "CISO";
            /// <summary>Duke Energy Progress East</summary>
            public const string DukeEnergyProgressEast = "CPLE";
            /// <summary>Duke Energy Progress West</summary>
            public const string DukeEnergyProgressWest = "CPLW";
            /// <summary>Arlington Valley, LLC</summary>
            public const string ArlingtonValleyLlc = "DEAA";
            /// <summary>PUD No. 1 of Douglas County</summary>
            public const string PudNo1OfDouglasCounty = "DOPD";
            /// <summary>Duke Energy Carolinas</summary>
            public const string DukeEnergyCarolinas = "DUK";
            /// <summary>Electric Energy, Inc.</summary>
            public const string ElectricEnergyInc = "EEI";
            /// <summary>El Paso Electric Company</summary>
            public const string ElPasoElectricCompany = "EPE";
            /// <summary>Electric Reliability Council of Texas, Inc.</summary>
            public const string ERCOT = "ERCO";
            /// <summary>Electric Reliability Council of Texas, Inc.</summary>
            public const string ElectricReliabilityCouncilOfTexasInc = "ERCO";
            /// <summary>Florida</summary>
            public const string Florida = "FLA";
            /// <summary>Florida Municipal Power Pool</summary>
            public const string FloridaMunicipalPowerPool = "FMPP";
            /// <summary>Duke Energy Florida, Inc.</summary>
            public const string DukeEnergyFloridaInc = "FPC";
            /// <summary>Florida Power &amp; Light Co.</summary>
            public const string FloridaPowerLightCo = "FPL";
            /// <summary>Public Utility District No. 2 of Grant County, Washington</summary>
            public const string PublicUtilityDistrictNo2OfGrantCountyWashington = "GCPD";
            /// <summary>GridLiance</summary>
            public const string GridLiance = "GLHB";
            /// <summary>Gridforce Energy Management, LLC</summary>
            public const string GridforceEnergyManagementLlc = "GRID";
            /// <summary>Griffith Energy, LLC</summary>
            public const string GriffithEnergyLlc = "GRIF";
            /// <summary>Gainesville Regional Utilities</summary>
            public const string GainesvilleRegionalUtilities = "GVL";
            /// <summary>NaturEner Power Watch, LLC</summary>
            public const string NaturEnerPowerWatchLlc = "GWA";
            /// <summary>New Harquahala Generating Company, LLC</summary>
            public const string NewHarquahalaGeneratingCompanyLlc = "HGMA";
            /// <summary>City of Homestead</summary>
            public const string CityOfHomestead = "HST";
            /// <summary>Imperial Irrigation District</summary>
            public const string ImperialIrrigationDistrict = "IID";
            /// <summary>Idaho Power Company</summary>
            public const string IdahoPowerCompany = "IPCO";
            /// <summary>ISO New England</summary>
            public const string ISONE = "ISNE";
            /// <summary>ISO New England</summary>
            public const string IsoNewEngland = "ISNE";
            /// <summary>JEA</summary>
            public const string Jea = "JEA";
            /// <summary>Los Angeles Department of Water and Power</summary>
            public const string LosAngelesDepartmentOfWaterAndPower = "LDWP";
            /// <summary>LG&amp;E and KU Services Company as agent for Louisville Gas and Electric Company and Kentucky Utilities Company</summary>
            public const string LgEAndKuServicesCompanyAsAgentForLouisvilleGasAndElectricCompanyAndKentuckyUtilitiesCompany = "LGEE";
            /// <summary>Mid-Atlantic</summary>
            public const string MidAtlantic = "MIDA";
            /// <summary>Midwest</summary>
            public const string Midwest = "MIDW";
            /// <summary>Midcontinent Independent System Operator, Inc.</summary>
            public const string MISO = "MISO";
            /// <summary>Midcontinent Independent System Operator, Inc.</summary>
            public const string MidcontinentIndependentSystemOperatorInc = "MISO";
            /// <summary>New England</summary>
            public const string NewEngland = "NE";
            /// <summary>Nevada Power Company</summary>
            public const string NevadaPowerCompany = "NEVP";
            /// <summary>Utilities Commission of New Smyrna Beach</summary>
            public const string UtilitiesCommissionOfNewSmyrnaBeach = "NSB";
            /// <summary>Northwest</summary>
            public const string Northwest = "NW";
            /// <summary>NorthWestern Corporation</summary>
            public const string NorthWesternCorporation = "NWMT";
            /// <summary>New York</summary>
            public const string NewYork = "NY";
            /// <summary>New York Independent System Operator</summary>
            public const string NYISO = "NYIS";
            /// <summary>New York Independent System Operator</summary>
            public const string NewYorkIndependentSystemOperator = "NYIS";
            /// <summary>PacifiCorp East</summary>
            public const string PacifiCorpEast = "PACE";
            /// <summary>PacifiCorp West</summary>
            public const string PacifiCorpWest = "PACW";
            /// <summary>Portland General Electric Company</summary>
            public const string PortlandGeneralElectricCompany = "PGE";
            /// <summary>PJM Interconnection, LLC</summary>
            public const string PJM = "PJM";
            /// <summary>PJM Interconnection, LLC</summary>
            public const string PjmInterconnectionLlc = "PJM";
            /// <summary>Public Service Company of New Mexico</summary>
            public const string PublicServiceCompanyOfNewMexico = "PNM";
            /// <summary>Public Service Company of Colorado</summary>
            public const string PublicServiceCompanyOfColorado = "PSCO";
            /// <summary>Puget Sound Energy, Inc.</summary>
            public const string PugetSoundEnergyInc = "PSEI";
            /// <summary>South Carolina Public Service Authority</summary>
            public const string SouthCarolinaPublicServiceAuthority = "SC";
            /// <summary>Dominion Energy South Carolina, Inc.</summary>
            public const string DominionEnergySouthCarolinaInc = "SCEG";
            /// <summary>Seattle City Light</summary>
            public const string SeattleCityLight = "SCL";
            /// <summary>Southeast</summary>
            public const string Southeast = "SE";
            /// <summary>Seminole Electric Cooperative</summary>
            public const string SeminoleElectricCooperative = "SEC";
            /// <summary>Southeastern Power Administration</summary>
            public const string SoutheasternPowerAdministration = "SEPA";
            /// <summary>Sikeston Board of Municipal Utilities</summary>
            public const string SikestonBoardOfMunicipalUtilities = "SIKE";
            /// <summary>Southern Company Services, Inc. - Trans</summary>
            public const string SouthernCompanyServicesIncTrans = "SOCO";
            /// <summary>Southwestern Power Administration</summary>
            public const string SouthwesternPowerAdministration = "SPA";
            /// <summary>Salt River Project Agricultural Improvement and Power District</summary>
            public const string SaltRiverProjectAgriculturalImprovementAndPowerDistrict = "SRP";
            /// <summary>Southwest</summary>
            public const string Southwest = "SW";
            /// <summary>Southwest Power Pool</summary>
            public const string SPP = "SWPP";
            /// <summary>Southwest Power Pool</summary>
            public const string SouthwestPowerPool = "SWPP";
            /// <summary>City of Tallahassee</summary>
            public const string CityOfTallahassee = "TAL";
            /// <summary>Tampa Electric Company</summary>
            public const string TampaElectricCompany = "TEC";
            /// <summary>Tennessee</summary>
            public const string Tennessee = "TEN";
            /// <summary>Tucson Electric Power</summary>
            public const string TucsonElectricPower = "TEPC";
            /// <summary>Texas</summary>
            public const string Texas = "TEX";
            /// <summary>Turlock Irrigation District</summary>
            public const string TurlockIrrigationDistrict = "TIDC";
            /// <summary>City of Tacoma, Department of Public Utilities, Light Division</summary>
            public const string CityOfTacomaDepartmentOfPublicUtilitiesLightDivision = "TPWR";
            /// <summary>Tennessee Valley Authority</summary>
            public const string TennesseeValleyAuthority = "TVA";
            /// <summary>United States Lower 48</summary>
            public const string UnitedStatesLower48 = "US48";
            /// <summary>Western Area Power Administration - Rocky Mountain Region</summary>
            public const string WesternAreaPowerAdministrationRockyMountainRegion = "WACM";
            /// <summary>Western Area Power Administration - Desert Southwest Region</summary>
            public const string WesternAreaPowerAdministrationDesertSouthwestRegion = "WALC";
            /// <summary>Western Area Power Administration - Upper Great Plains West</summary>
            public const string WesternAreaPowerAdministrationUpperGreatPlainsWest = "WAUW";
            /// <summary>NaturEner Wind Watch, LLC</summary>
            public const string NaturEnerWindWatchLlc = "WWA";
            /// <summary>Alcoa Power Generating, Inc. - Yadkin Division</summary>
            public const string AlcoaPowerGeneratingIncYadkinDivision = "YAD";
        }
    }
}
