#!/usr/bin/env python3
"""
Generates EIA.BalancingAuthorities.cs: readable named constants for the EIA-930 balancing
authority codes, for use as the ticker in AddData<EIAElectricity>(EIA.BalancingAuthorities.X).
Mirrors the BEA.Industries / USEnergy.Petroleum helper pattern.

Source of truth: the live respondent facet of electricity/rto/region-data.
Run: EIA_API_KEY=... python generate_balancing_authorities.py
"""
import os
import re
import sys
import json
import urllib.request

FACET = "https://api.eia.gov/v2/electricity/rto/region-data/facet/respondent/"
KEY = os.environ.get("EIA_API_KEY", "")

# The handful of operators traders actually name out loud. The facet gives us the legal entity
# name ("Electric Reliability Council of Texas, Inc."), which generates a correct but unusable
# constant, so these get a short alias alongside the derived one.
ALIASES = {
    "ERCO": "ERCOT",
    "CISO": "CAISO",
    "NYIS": "NYISO",
    "ISNE": "ISONE",
    "SWPP": "SPP",
    "BPAT": "BPA",
    # PJM and MISO already read as the operator, but their legal name does not
    # ("PJM Interconnection, LLC" -> PjmInterconnectionLlc), so alias them too.
    "PJM": "PJM",
    "MISO": "MISO",
}


def fetch_respondents():
    url = f"{FACET}?api_key={KEY}"
    with urllib.request.urlopen(url, timeout=60) as r:
        data = json.load(r)
    return data["response"]["facets"]


def xml_escape(text: str) -> str:
    # Respondent names carry ampersands ("Florida Power & Light Co.", "LG&E and KU Services"),
    # which the C# doc comment would reject as an undefined entity.
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def to_identifier(desc: str) -> str:
    # PascalCase, the naming used across the datasets. Each word starts upper; a word the source
    # wrote in full caps drops the rest, the way EODHD spells Gdp and USEnergy spells Spr.
    words = [w for w in re.split(r"[^0-9A-Za-z]+", desc.strip()) if w]
    ident = "".join(w.capitalize() if w.isupper() else w[:1].upper() + w[1:] for w in words)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    return ident


def main():
    if not KEY:
        print("EIA_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    rows = fetch_respondents()
    codes = {r["id"].strip() for r in rows}
    missing = sorted(set(ALIASES) - codes)
    if missing:
        print(f"aliased codes no longer in the facet: {missing}", file=sys.stderr)
        sys.exit(1)

    seen = set()
    entries = []
    for r in sorted(rows, key=lambda x: x["id"]):
        code = r["id"].strip()
        name = r["name"].strip()
        alias = ALIASES.get(code)
        if alias:
            entries.append((alias, code, name))
            seen.add(alias)
        ident = to_identifier(name)
        # Disambiguate collisions by appending the code, which keeps the casing EIA gives it: it
        # is an identifier, not a word to title-case.
        if ident in seen:
            ident = f"{ident}{re.sub(r'[^A-Za-z0-9]', '', code)}"
        seen.add(ident)
        entries.append((ident, code, name))

    lines = []
    lines.append("/*")
    lines.append(" * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.")
    lines.append(" * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.")
    lines.append(" *")
    lines.append(" * Licensed under the Apache License, Version 2.0 (the \"License\");")
    lines.append(" * you may not use this file except in compliance with the License.")
    lines.append(" * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0")
    lines.append(" *")
    lines.append(" * Unless required by applicable law or agreed to in writing, software")
    lines.append(" * distributed under the License is distributed on an \"AS IS\" BASIS,")
    lines.append(" * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.")
    lines.append(" * See the License for the specific language governing permissions and")
    lines.append(" * limitations under the License.")
    lines.append("*/")
    lines.append("")
    lines.append("// AUTO-GENERATED by DataProcessing/generate_balancing_authorities.py - do not edit by hand.")
    lines.append("// Constant names are derived from the EIA respondent name; values are EIA-930 codes.")
    lines.append("")
    lines.append("namespace QuantConnect.DataSource")
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// Readable named constants for EIA-930 balancing authority codes, for use as the ticker in")
    lines.append("    /// <c>AddData&lt;EIAElectricity&gt;(EIA.BalancingAuthorities.X)</c>. The major operators also")
    lines.append("    /// carry their common short name (ERCOT, CAISO, NYISO, ISONE, SPP, BPA).")
    lines.append("    /// </summary>")
    lines.append("    public static partial class EIA")
    lines.append("    {")
    lines.append("        /// <summary>EIA-930 balancing authority codes by readable name.</summary>")
    lines.append("        public static class BalancingAuthorities")
    lines.append("        {")
    for ident, code, name in entries:
        lines.append(f"            /// <summary>{xml_escape(name)}</summary>")
        lines.append(f"            public const string {ident} = \"{code}\";")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")

    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "EIA.BalancingAuthorities.cs")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out} with {len(entries)} constants for {len(rows)} balancing authorities")


if __name__ == "__main__":
    main()
